# Generated by Django 5.2.5 on 2025-09-03 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hrana', 'Hrana'), ('smjestaj', 'Smještaj'), ('prijevoz', 'Prijevoz'), ('zabava', 'Zabava'), ('ostalo', 'Ostalo')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financije.monthlydata')),
            ],
        ),
    ]
